// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	drafts "github.com/paketo-buildpacks/pipeline-builder/v2/drafts"
	mock "github.com/stretchr/testify/mock"
)

// BuildModuleLoader is an autogenerated mock type for the BuildModuleLoader type
type BuildModuleLoader struct {
	mock.Mock
}

// LoadBuildpack provides a mock function with given fields: id
func (_m *BuildModuleLoader) LoadBuildpack(id string) (drafts.Buildpack, error) {
	ret := _m.Called(id)

	var r0 drafts.Buildpack
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (drafts.Buildpack, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) drafts.Buildpack); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(drafts.Buildpack)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadBuildpacks provides a mock function with given fields: uris
func (_m *BuildModuleLoader) LoadBuildpacks(uris []string) ([]drafts.Buildpack, error) {
	ret := _m.Called(uris)

	var r0 []drafts.Buildpack
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]drafts.Buildpack, error)); ok {
		return rf(uris)
	}
	if rf, ok := ret.Get(0).(func([]string) []drafts.Buildpack); ok {
		r0 = rf(uris)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]drafts.Buildpack)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(uris)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadExtension provides a mock function with given fields: id
func (_m *BuildModuleLoader) LoadExtension(id string) (drafts.Extension, error) {
	ret := _m.Called(id)

	var r0 drafts.Extension
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (drafts.Extension, error)); ok {
		return rf(id)
	}
	if rf, ok := ret.Get(0).(func(string) drafts.Extension); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Get(0).(drafts.Extension)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// LoadExtensions provides a mock function with given fields: uris
func (_m *BuildModuleLoader) LoadExtensions(uris []string) ([]drafts.Extension, error) {
	ret := _m.Called(uris)

	var r0 []drafts.Extension
	var r1 error
	if rf, ok := ret.Get(0).(func([]string) ([]drafts.Extension, error)); ok {
		return rf(uris)
	}
	if rf, ok := ret.Get(0).(func([]string) []drafts.Extension); ok {
		r0 = rf(uris)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]drafts.Extension)
		}
	}

	if rf, ok := ret.Get(1).(func([]string) error); ok {
		r1 = rf(uris)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBuildModuleLoader creates a new instance of BuildModuleLoader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBuildModuleLoader(t interface {
	mock.TestingT
	Cleanup(func())
}) *BuildModuleLoader {
	mock := &BuildModuleLoader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
