name: Tests
"on":
    merge_group:
        types:
            - checks_requested
        branches:
            - main
    pull_request: {}
    push:
        branches:
            - main
jobs:
    integration:
        name: Integration Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                path: ${{ env.HOME }}/go/pkg/mod
                restore-keys: ${{ runner.os }}-go-
            - uses: actions/setup-go@v5
              with:
                go-version: "1.20"
            - name: Install create-package
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                go install -ldflags="-s -w" github.com/paketo-buildpacks/libpak/cmd/create-package@latest
            - name: Install pack
              run: |
                #!/usr/bin/env bash
                # this is coming from a copy of https://github.com/buildpacks/pack/actions/runs/8118576298 stored on box
                # TODO to revisit when the official one is out
                set -euo pipefail

                echo "Installing pack experimental"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl -L "https://ent.box.com/shared/static/j4d1bfe9uk1sb0i7zjvci0md9xmy41u4" -o ${HOME}/bin/pack
                chmod +x "${HOME}"/bin/pack
            - name: Enable pack Experimental
              if: ${{ false }}
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Enabling pack experimental features"

                mkdir -p "${HOME}"/.pack
                echo "experimental = true" >> "${HOME}"/.pack/config.toml
            - name: Install richgo
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing richgo ${RICHGO_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  "https://github.com/kyoh86/richgo/releases/download/v${RICHGO_VERSION}/richgo_${RICHGO_VERSION}_linux_amd64.tar.gz" \
                | tar -C "${HOME}"/bin -xz richgo
              env:
                RICHGO_VERSION: 0.3.10
            - name: Run Tests
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                richgo test ./integration/... -run Integration
              env:
                RICHGO_FORCE_COLOR: "1"
    unit:
        name: Unit Test
        runs-on:
            - ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/cache@v4
              with:
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                path: ${{ env.HOME }}/go/pkg/mod
                restore-keys: ${{ runner.os }}-go-
            - uses: actions/setup-go@v5
              with:
                go-version: "1.20"
            - name: Install richgo
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                echo "Installing richgo ${RICHGO_VERSION}"

                mkdir -p "${HOME}"/bin
                echo "${HOME}/bin" >> "${GITHUB_PATH}"

                curl \
                  --location \
                  --show-error \
                  --silent \
                  "https://github.com/kyoh86/richgo/releases/download/v${RICHGO_VERSION}/richgo_${RICHGO_VERSION}_linux_amd64.tar.gz" \
                | tar -C "${HOME}"/bin -xz richgo
              env:
                RICHGO_VERSION: 0.3.10
            - name: Run Tests
              run: |
                #!/usr/bin/env bash

                set -euo pipefail

                richgo test ./... -run Unit
              env:
                RICHGO_FORCE_COLOR: "1"
